name: cleanup old images
on:
    workflow_call:
        inputs:
            project:
                required: true
                type: string

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
          - uses: dataaxiom/ghcr-cleanup-action@v1
            with:
                keep-n-tagged: 3
