name: deploy to vps
on:
    workflow_call:
        inputs:
            project:
                required: true
                type: string
            drain:
                required: false
                type: boolean
                default: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # This is needed while GitHub doesn't support IPv6
            - name: Set up WARP
              uses: fscarmen/warp-on-actions@v1.4
              with:
                  stack: dual # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
                  mode: client # Optional. Support [ wireguard, client ]. Default is wireguard.

            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup SSH key
              env:
                  SSH_PORT: ${{ secrets.SSH_PORT }}
                  SSH_SERVER: ${{ secrets.SSH_SERVER }}
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  eval $(ssh-agent -s)
                  ssh-add ~/.ssh/id_ed25519 > /dev/null 2>&1
                  ssh-keyscan -p "$SSH_PORT" "$SSH_SERVER" >> ~/.ssh/known_hosts

            - name: Deploy
              env:
                  DOCKER_HOST: ${{ secrets.SSH_HOST }}
              run: |
                  # Login to ghcr
                  docker login -u V4ldum -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

                  # Pull new images
                  docker compose pull

                  # Iterate over services
                  SERVICES=$(docker compose config --services)
                  for SERVICE in $SERVICES; do
                    ## Scale up service
                    docker compose up -d --no-deps --scale "$SERVICE"=2 --no-recreate ${{ inputs.project }}

                    ## Get container IDs
                    OLD=$(docker ps -f "name=$SERVICE" --format "{{.ID}} {{.CreatedAt}}" | sort -k2 | head -n 1 | awk '{print $1}')
                    NEW=$(docker ps -f "name=$SERVICE" --format "{{.ID}} {{.CreatedAt}}" | sort -k2 | tail -n 1 | awk '{print $1}')

                    ## Wait for container to be up
                    for attempt in {1..6}; do
                      sleep 5
                      CODE=$(docker inspect --format "{{.State.ExitCode}}" "$NEW")
                      if [ "$CODE" = "0" ]; then
                        break
                      fi
                    done

                    ## Scale down
                    CODE=$(docker inspect --format "{{.State.ExitCode}}" "$NEW")
                    if [ "$CODE" = "0" ]; then
                      ### Drain old container
                      if [ "${{ inputs.drain }}" = "true" ]; then
                        docker exec "$OLD" /bin/touch /tmp/drain
                        sleep 10
                      fi

                      ### Delete old and scale down if healthy
                      docker container rm -f "$OLD"
                      docker compose up -d --no-deps --scale $SERVICE=1 --no-recreate $SERVICE

                      docker rename "$NEW" ${{ inputs.project }}
                    else
                      # Delete new and scale down if unhealthy
                      docker logs "$NEW"
                      docker container rm -f "$NEW"
                      docker compose up -d --no-deps --scale $SERVICE=1 --no-recreate $SERVICE
                      exit 1
                    fi
                  done
