name: test static-shock project
on:
    workflow_call:
        inputs:
            enabled:
                required: false
                type: boolean
                default: true

jobs:
    run-tests:
        if: inputs.enabled
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1

            - name: Config Flutter
              run: dart --disable-analytics

            - name: Install dependencies
              run: dart pub get

            - name: Analyze project source
              run: dart analyze
